DROP TABLE "AFFECTATION";
DROP TABLE "PERSONNELRESIDENT";
DROP TABLE "CONTACTRESIDENT";
DROP TABLE "INVITERENDEZVOUS";
DROP TABLE "RENDEZVOUS";
DROP TABLE "TABLETTE";
DROP TABLE "CRENEAUVISIO";
DROP TABLE "INVITE";
DROP TABLE "RESIDENT";
DROP TABLE "CONTACT";
DROP TABLE "PERSONNEL";
DROP TABLE "UTILISATEUR";
DROP TABLE "PERSONNE";
DROP TABLE "UNITE";
DROP TABLE "ETABLISSEMENT";

/*CREATION DES TABLES PRIMAIRES*/
CREATE TABLE "ETABLISSEMENT" 
(
    "IDETABLISSEMENT"               RAW(16) NOT NULL,
    "NOMETABLISSEMENT"              VARCHAR(50) NOT NULL,
    "NUMEROTELEPHONEETABLISSEMENT"  CHAR(10) NOT NULL,
    "ADRESSEMAILETABLISSEMENT"      VARCHAR2(100) NOT NULL,
    "RUEETABLISSEMENT"              VARCHAR2(100) NOT NULL,
    "CODEPOSTALETABLISSEMENT"       NUMBER(5) DEFAULT 00000,
    "VILLEETABLISSEMENT"            VARCHAR2(50) NOT NULL,
    "PAYSETABLISSEMENT"             VARCHAR2(50) DEFAULT 'FRANCE',
    "NBPLACES"                      NUMBER(4) DEFAULT 0,
    "NBUNITESOFF"                   NUMBER(3) DEFAULT 0,
    CONSTRAINT PK_ETABLISSEMENT PRIMARY KEY("IDETABLISSEMENT")
);

CREATE TABLE "PERSONNE"
(
    "IDPERSONNE"        RAW(16) NOT NULL,
    "NOMPERSONNE"       VARCHAR2(50) NOT NULL,
    "PRENOMPERSONNE"    VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_PERSONNE PRIMARY KEY("IDPERSONNE")
);

CREATE TABLE "UTILISATEUR"(
    "IDUTILISATEUR"                 RAW(16) NOT NULL,
    "NUMEROTELEPHONEUTILISATEUR"    CHAR(10) NOT NULL,
    "ADRESSEMAILUTILISATEUR"        VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_UTILISATEUR PRIMARY KEY ("IDUTILISATEUR"),
    CONSTRAINT FK_PERSONNE_UTILISATEUR FOREIGN KEY ("IDUTILISATEUR") REFERENCES "PERSONNE"("IDPERSONNE"),
    CONSTRAINT C8_MAILUTIL_UNIQUE UNIQUE ("ADRESSEMAILUTILISATEUR")
);

CREATE TABLE "INVITE"(
    "IDINVITE"          RAW(16) NOT NULL,
    "ADRESSEMAILINVITE" VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_INVITE PRIMARY KEY ("IDINVITE"),
    CONSTRAINT FK_PERSONNE_INVITE FOREIGN KEY ("IDINVITE") REFERENCES "PERSONNE"("IDPERSONNE"),
    CONSTRAINT C9_MAILINV_UNIQUE UNIQUE ("ADRESSEMAILINVITE")
);

CREATE TABLE "PERSONNEL"
(
    "IDPERSONNEL"    RAW(16) NOT NULL,
    "FONCTION"       VARCHAR(50) NOT NULL,
    CONSTRAINT PK_PERSONNEL PRIMARY KEY ("IDPERSONNEL"),
    CONSTRAINT FK_UTILISATEUR_PERSONNEL FOREIGN KEY("IDPERSONNEL") REFERENCES "UTILISATEUR" ("IDUTILISATEUR")
);

CREATE TABLE "CONTACT"
(
    "IDCONTACT"     RAW(16) NOT NULL,
    "COMPTEVALIDE"  NUMBER(1) NOT NULL,
    CONSTRAINT PK_CONTACT PRIMARY KEY ("IDCONTACT"),
    CONSTRAINT FK_PERSONNE_CONTACT FOREIGN KEY("IDCONTACT") REFERENCES "UTILISATEUR" ("IDUTILISATEUR"),
    CONSTRAINT C7_VALIDITE_CONTACT CHECK (COMPTEVALIDE IN (0,1))
);

CREATE TABLE "UNITE"
(
    "IDUNITE"   RAW(16) NOT NULL,
    "IDETABLISSEMENT" RAW(16) NOT NULL,
    "NOMUNITE"  VARCHAR2(50) NOT NULL,
    "ETATUNITE" VARCHAR2(20) DEFAULT 'OUVERTE',
    CONSTRAINT PK_UNITE PRIMARY KEY("IDUNITE"),
    CONSTRAINT FK_ETABLISSEMENT_UNITE FOREIGN KEY ("IDETABLISSEMENT") REFERENCES "ETABLISSEMENT"("IDETABLISSEMENT"),
    CONSTRAINT C1_STATUSRESIDENT CHECK (ETATUNITE IN ('OUVERTE', 'FERMEE', 'DEJOUR', 'CONTAGIEUSE'))
);

CREATE TABLE "RESIDENT"
(
    "IDRESIDENT"            RAW(16) NOT NULL,
    "IDUNITE"               RAW(16) NOT NULL,
    "IDPERSONNEL"           RAW(16) NOT NULL,
    "DATENAISSANCERESIDENT" DATE NOT NULL,
    "STATUTRESIDENT"        VARCHAR2(20) DEFAULT 'DISPONIBLE',
    CONSTRAINT PK_RESIDENT PRIMARY KEY ("IDRESIDENT"),
    CONSTRAINT FK_PERSONNE_RESIDENT FOREIGN KEY ("IDRESIDENT") REFERENCES "PERSONNE"("IDPERSONNE"),
    CONSTRAINT FK_PERSONNEL_RESIDENT FOREIGN KEY ("IDPERSONNEL") REFERENCES "PERSONNEL"("IDPERSONNEL"),
    CONSTRAINT FK_UNITE_RESIDENT FOREIGN KEY ("IDUNITE") REFERENCES "UNITE"("IDUNITE"),
    CONSTRAINT C2_STATUTRESIDENT CHECK (STATUTRESIDENT IN ('DISPONIBLE', 'INDISPONIBLE', 'ANCIENRESIDENT'))
);

CREATE TABLE "CRENEAUVISIO"
(
    "IDCRENEAU"         RAW(16) NOT NULL,
    "IDPERSONNEL"       RAW(16) NOT NULL,
    "DATECRENEAU"       TIMESTAMP NOT NULL,
    "DISPONIBLE"        NUMBER(1) DEFAULT 1,
    "DUREECRENEAU"      NUMBER(2) DEFAULT 30,
    CONSTRAINT PK_CRENEAU PRIMARY KEY("IDCRENEAU"),
    CONSTRAINT AK_CRENEAU1 UNIQUE("DATECRENEAU"),
    CONSTRAINT FK_PERSONNEL_CRENEAU FOREIGN KEY ("IDPERSONNEL") REFERENCES "PERSONNEL"("IDPERSONNEL"),
    CONSTRAINT C3_CRENEAUDISPO CHECK (DISPONIBLE IN (0,1))
);

CREATE TABLE "TABLETTE"
(
    "IDTABLETTE"    RAW(16) NOT NULL,
    "ETATTABLETTE"  VARCHAR2(20) DEFAULT 'ENCHARGEMENT',
    CONSTRAINT PK_TABLETTE PRIMARY KEY ("IDTABLETTE"),
    CONSTRAINT C6_ETATTAB CHECK (ETATTABLETTE IN ('ENCHARGEMENT', 'HS'))
);

CREATE TABLE "RENDEZVOUS"
(
    "IDRENDEZVOUS"      RAW(16) NOT NULL,
    "IDRESIDENT"        RAW(16) NOT NULL,
    "IDCRENEAU"         RAW(16) NOT NULL,
    "IDCONTACT"         RAW(16) NOT NULL,
    "IDTABLETTE"        RAW(16) NOT NULL,
    "IDREMPLACANT"      RAW(16) NULL,
    "DATECRENEAU"       TIMESTAMP NOT NULL,
    "HEUREDEBUTRDV"     VARCHAR2(8) NULL,
    "HEUREFINRDV"       VARCHAR2(8) NULL,
    "STATUTRENDEZVOUS"  VARCHAR2(15) DEFAULT 'NORMAL',
    "ETATRENDEZVOUS"    VARCHAR2(20) DEFAULT 'PROGRAMME',
    "AVISNBETOILE"      NUMBER(1) DEFAULT 0,
    "COMMENTAIRE"       VARCHAR2(500) NULL,
    CONSTRAINT PK_RENDEZVOUS PRIMARY KEY ("IDRENDEZVOUS"),
    CONSTRAINT FK_RESIDENT_RENDEZVOUS FOREIGN KEY ("IDRESIDENT") REFERENCES "RESIDENT"("IDRESIDENT"),
    CONSTRAINT FK_CRENEAU1_RENDEZVOUS FOREIGN KEY ("IDCRENEAU") REFERENCES "CRENEAUVISIO"("IDCRENEAU"),
    CONSTRAINT FK_TABLETTE_RENDEZVOUS FOREIGN KEY ("IDTABLETTE") REFERENCES "TABLETTE"("IDTABLETTE"),
    CONSTRAINT FK_CONTACT_RENDEZVOUS FOREIGN KEY ("IDCONTACT") REFERENCES "CONTACT"("IDCONTACT"),
    CONSTRAINT FK_REMPLACANT_RENDEZVOUS FOREIGN KEY ("IDREMPLACANT") REFERENCES "PERSONNEL"("IDPERSONNEL"),
    CONSTRAINT FK_CRENEAU2_RENDEZVOUS FOREIGN KEY ("DATECRENEAU") REFERENCES "CRENEAUVISIO"("DATECRENEAU"),
    CONSTRAINT C4_STATUTRDV CHECK (STATUTRENDEZVOUS IN ('NORMAL', 'EXCEPTIONNEL')),
    CONSTRAINT C5_ETATRDV CHECK (ETATRENDEZVOUS IN ('PROGRAMME', 'VALIDE', 'ANNULE', 'TERMINE'))
);

/*CREATION DES TABLES RELATIONNELLES*/
CREATE TABLE "CONTACTRESIDENT"
(
    "IDRESIDENT"    RAW(16) NOT NULL,
    "IDCONTACT"     RAW(16) NOT NULL,
    FOREIGN KEY("IDRESIDENT") REFERENCES "RESIDENT"("IDRESIDENT"),
    FOREIGN KEY("IDCONTACT") REFERENCES "CONTACT"("IDCONTACT")
);

CREATE TABLE "INVITERENDEZVOUS"
(
    "IDINVITE"      RAW(16) NOT NULL,
    "IDRENDEZVOUS"  RAW(16) NOT NULL,
    CONSTRAINT FK_IR_INVITE FOREIGN KEY("IDINVITE") REFERENCES "INVITE"("IDINVITE"),
    CONSTRAINT FK_IR_RENDEZVOUS FOREIGN KEY("IDRENDEZVOUS") REFERENCES "RENDEZVOUS"("IDRENDEZVOUS")
);

CREATE TABLE "AFFECTATION"
(
    "IDAFFECTATION" RAW(16) NOT NULL,
    "IDPERSONNEL"   RAW(16) NOT NULL,
    "IDUNITE"       RAW(16) NOT NULL,
    "DATEDEBUT"     TIMESTAMP NOT NULL,
    "DATEFIN"       TIMESTAMP NULL,
    CONSTRAINT PK_AFFECTATION PRIMARY KEY("IDAFFECTATION"),
    CONSTRAINT FK_PERSONNEL_AFFECTATION FOREIGN KEY("IDPERSONNEL") REFERENCES "PERSONNEL"("IDPERSONNEL"),
    CONSTRAINT FK_UNITE_AFFECTATION FOREIGN KEY("IDUNITE") REFERENCES "UNITE"("IDUNITE")
);

CREATE TABLE "PERSONNELRESIDENT"
(
    "IDPERSONNELRESIDENT"   RAW(16) NOT NULL,
    "IDRESIDENT"            RAW(16) NOT NULL,
    "IDPERSONNEL"           RAW(16) NOT NULL,
    "DATEDEBUT"             TIMESTAMP NOT NULL,
    "DATEFIN"               TIMESTAMP NULL,
    CONSTRAINT PK_PERSONNELRESIDENT PRIMARY KEY("IDPERSONNELRESIDENT"),
    CONSTRAINT FK_RESIDENT_PR FOREIGN KEY("IDRESIDENT") REFERENCES "RESIDENT"("IDRESIDENT"),
    CONSTRAINT FK_PERSONNEL_PR FOREIGN KEY("IDPERSONNEL") REFERENCES "PERSONNEL"("IDPERSONNEL")
);

CREATE INDEX Etablissement_Mail ON "ETABLISSEMENT"("ADRESSEMAILETABLISSEMENT");
CREATE INDEX Etablissement_Identite ON "ETABLISSEMENT"("NOMETABLISSEMENT","VILLEETABLISSEMENT","RUEETABLISSEMENT");
CREATE INDEX Unite_Nom ON "UNITE"("NOMUNITE"); 
CREATE INDEX Personne_Identite ON "PERSONNE"("NOMPERSONNE", "PRENOMPERSONNE");
CREATE INDEX Invite_Mail ON "INVITE"("ADRESSEMAILINVITE");
CREATE INDEX User_Mail ON "UTILISATEUR"("ADRESSEMAILUTILISATEUR");
CREATE INDEX Resident_Statut ON "RESIDENT"("STATUTRESIDENT");
CREATE INDEX RDV_Etat ON "RENDEZVOUS"("ETATRENDEZVOUS");
CREATE INDEX Creneau_Date ON "CRENEAUVISIO"("DATECRENEAU");
CREATE INDEX Creneau_Dispo ON "CRENEAUVISIO"("DISPONIBLE");
CREATE INDEX Compte_Valide ON "CONTACT"("COMPTEVALIDE");